export const CLOCK_IN_REQUEST = "CLOCK_IN_REQUEST";
export const CLOCK_IN_SUCCESS = "CLOCK_IN_SUCCESS";
export const CLOCK_IN_FAIL = "CLOCK_IN_FAIL";

export const CLOCK_OUT_REQUEST = "CLOCK_OUT_REQUEST";
export const CLOCK_OUT_SUCCESS = "CLOCK_OUT_SUCCESS";
export const CLOCK_OUT_FAIL = "CLOCK_OUT_FAIL";

export const GET_ALL_CLOCK_INS_REQUEST = "GET_ALL_CLOCK_INS_REQUEST";
export const GET_ALL_CLOCK_INS_SUCCESS = "GET_ALL_CLOCK_INS_SUCCESS";
export const GET_ALL_CLOCK_INS_FAIL = "GET_ALL_CLOCK_INS_FAIL";

export const GET_ALL_CLOCK_OUTS_REQUEST = "GET_ALL_CLOCK_OUTS_REQUEST";
export const GET_ALL_CLOCK_OUTS_SUCCESS = "GET_ALL_CLOCK_OUTS_SUCCESS";
export const GET_ALL_CLOCK_OUTS_FAIL = "GET_ALL_CLOCK_OUTS_FAIL";

export const CLOCK_IN_RESET = "CLOCK_IN_RESET";
export const CLOCK_OUT_RESET = "CLOCK_OUT_RESET";
